package legstar.samples.custdat;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Map;

import com.legstar.base.context.CobolContext;
import com.legstar.base.context.EbcdicCobolContext;
import com.legstar.base.converter.Cob2HashMapConverter;
import com.legstar.base.converter.FromHostResult;

/**
 * Sample code that invokes a converter to transform host data read off a file
 * into a java Hash Map.
 * <p>
 * This sample uses the {@link CobolCustomerData} class that was generated by
 * the legstar base generator starting from the CUSTDAT COBOL copybook.
 * <p>
 * In this sample the host data is read from a file for convenience but it could
 * come from any source (RPC, JMS, ...).
 *
 */
public class CustdatSample {

    public static void main(final String[] args) {
        CustdatSample main = new CustdatSample();
        main.convert(args[0]);
    }

    public void convert(String filePath) {

        // Characteristics of the mainframe data (such as code page)
        CobolContext cobolContext = new EbcdicCobolContext();

        // COBOL structure model (generated by legstar-base-generator)
        CobolCustomerData cobolComplexType = new CobolCustomerData();

        // Create a reusable, thread safe, converter.
        Cob2HashMapConverter converter = new Cob2HashMapConverter.Builder()
                .cobolContext(cobolContext)
                .cobolComplexType(cobolComplexType)
                .build();

        // Get mainframe data (file, RPC, JMS, ...)
        byte[] hostData = readSampleData(filePath);

        // Convert the mainframe data to java
        FromHostResult < Map < String, Object > > result = converter
                .convert(hostData);

        // Print out the result hash map
        System.out.println("Hash map: " + result.getValue());

    }
    
    /**
     * Sample mainframe data for a single record come from a file.
     * <p>
     * In a real situation there would be more than one record in the file but
     * we keep things simple here.
     * 
     * @return a buffer full of mainframe data
     */
    private byte[] readSampleData(String filePath) {
        File sampleFile = new File(filePath);
        byte[] buffer = new byte[(int) sampleFile.length()];
        FileInputStream fis = null;
        try {
            fis = new FileInputStream(sampleFile);
            readFill(fis, buffer);
        } catch (IOException e) {
            throw new RuntimeException(e);
        } finally {
            try {
                fis.close();
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
        return buffer;
    }

    /**
     * Fill a buffer with raw bytes read off a stream.
     * 
     * @param stream the input stream
     * @param buffer to fill with bytes to read off the stream
     * @return bytes read (might be smaller than buffer length at EOF)
     * @throws IOException if unable to read the stream
     */
    private int readFill(InputStream stream, byte[] buffer)
            throws IOException {
        int r = buffer.length;
        while (r > 0) {
            int p = buffer.length - r;
            int c = stream.read(buffer, p, r);
            if (c == -1) {
                break;
            }
            r -= c;
        }
        return buffer.length - r;

    }

}
